### PR TITLE
fix build with boost 1.87

### PR DESCRIPTION
**Pull request by milahu**
kademlia 4ccfd508f1b50734ff9f4c1db3c5b3bb48bdb404 fails to build with boost 1.87

```
nix-shell -p git cmake boost187
git clone https://github.com/DavidKeller/kademlia
cd kademlia
git checkout 4ccfd508f1b50734ff9f4c1db3c5b3bb48bdb404
mkdir build
cd build
BUILD_TESTING=1 cmake .. && LANG=C make
```

```
In file included from /home/user/src/libtorrent/libtorrent-issue7926-2/kademlia/src/kademlia/first_session.cpp:28:
/home/user/src/libtorrent/libtorrent-issue7926-2/kademlia/src/kademlia/session_impl.hpp:37:10: fatal error: boost/asio/io_service.hpp: No such file or directory
   37 | #include <boost/asio/io_service.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### quickfix

use boost 1.86

### similar issues

similar issue: https://github.com/rstudio/rstudio/issues/15688#issuecomment-2649062076

> The build logs also have:
> 
> ```
> /build/rstudio-desktop/src/rstudio-2024.12.0-467/src/cpp/core/include/core/http/AsyncClient.hpp:24:10: fatal error: boost/asio/io_service.hpp: No such file or directory
>    24 | #include <boost/asio/io_service.hpp>
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> ```
> 
> Is Boost.Asio missing from your Boost installation for some reason?

> It looks like it was removed, alongside a lot of other deprecated classes. [chriskohlhoff/asio@49fcd03](https://github.com/chriskohlhoff/asio/commit/49fcd03434e8d43271522fe8d360558b5974ce83)
> 
> Unfortunately, it will probably take some time for us to accommodate these changes.

similar issue: https://github.com/The-OpenROAD-Project/OpenROAD/issues/6373

similar issue: https://github.com/monero-project/monero/issues/9596

### actual fix

trying to fix kademlia ...

documenting this here
because i found no guide for porting from boost 1.86 to boost 1.87

> `sed -i 's/boost::asio::ip::address::from_string/boost::asio::ip::make_address/g' src/kademlia/ip_endpoint.hpp test/unit_tests/*.?pp`

```
In file included from /home/user/src/libtorrent/libtorrent-issue7926-2/kademlia/src/kademlia/first_session.cpp:28:
/home/user/src/libtorrent/libtorrent-issue7926-2/kademlia/src/kademlia/session_impl.hpp:37:10: fatal error: boost/asio/io_service.hpp: No such file or directory
   37 | #include <boost/asio/io_service.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

https://github.com/rstudio/rstudio/pull/15739

```diff
-#include <boost/asio/io_service.hpp>
+#include <boost/asio/io_context.hpp>
```

```
In file included from /home/user/src/libtorrent/libtorrent-issue7926-2/kademlia/src/kademlia/session_impl.hpp:40,
                 from /home/user/src/libtorrent/libtorrent-issue7926-2/kademlia/src/kademlia/first_session.cpp:28:
/home/user/src/libtorrent/libtorrent-issue7926-2/kademlia/src/kademlia/message_socket.hpp:72:24: error: 'boost::asio::io_service' has not been declared
   72 |         ( boost::asio::io_service & io_service
      |                        ^~~~~~~~~~
```

```diff
-boost::asio::io_service
+boost::asio::io_context
```

```
In file included from /home/user/src/libtorrent/libtorrent-issue7926-2/kademlia/src/kademlia/first_session.cpp:28:
/home/user/src/libtorrent/libtorrent-issue7926-2/kademlia/src/kademlia/session_impl.hpp: In member function 'void kademlia::detail::session_impl::abort()':
/home/user/src/libtorrent/libtorrent-issue7926-2/kademlia/src/kademlia/session_impl.hpp:154:21: error: 'class boost::asio::io_context' has no member named 'post'
  154 |         io_service_.post( service_stopper );
      |                     ^~~~
```

```diff
-        io_service_.post( perform_read );
+        boost::asio::post( io_service_, perform_read );
```

```
/home/user/src/libtorrent/libtorrent-issue7926-2/kademlia/src/kademlia/message_socket.hpp:346:58: error: no type named 'query' in 'boost::asio::ip::udp::resolver' {aka 'class boost::asio::ip::basic_resolver<boost::asio::ip::udp>'}
  346 |     typename protocol_type::resolver::query::flags const f{};
      |                                                          ^
```

https://www.boost.org/doc/libs/1_87_0/doc/html/boost_asio/reference/ip__basic_resolver/resolve.html

https://www.boost.org/doc/libs/1_87_0/doc/html/boost_asio/reference/ip__address_v4/make_address_v4/overload3.html

```
In file included from /home/user/src/libtorrent/libtorrent-issue7926-2/kademlia/test/unit_tests/test_fake_socket.cpp:33:
/home/user/src/libtorrent/libtorrent-issue7926-2/kademlia/test/fake_socket.hpp: In member function 'void kademlia::test::fake_socket::log_packet(const boost::asio::const_buffer&, const endpoint_type&)':
/home/user/src/libtorrent/libtorrent-issue7926-2/kademlia/test/fake_socket.hpp:418:31: error: 'buffer_cast' is not a member of 'boost::asio'; did you mean 'buffer_copy'?
  418 |         auto i = boost::asio::buffer_cast< uint8_t const * >( buffer );
      |                               ^~~~~~~~~~~
      |                               buffer_copy
```

```diff
-        auto i = boost::asio::buffer_cast< uint8_t const * >( buffer );
+        auto i = static_cast< uint8_t const * >( buffer.data() );
```

```
/home/user/src/libtorrent/libtorrent-issue7926-2/kademlia/test/unit_tests/test_fake_socket.cpp: In member function 'void {anonymous}::fake_socket::test_construction::can_send_and_receive_messages::test_method()':
/home/user/src/libtorrent/libtorrent-issue7926-2/kademlia/test/unit_tests/test_fake_socket.cpp:104:20: error: 'work' is not a member of 'boost::asio::io_context'
  104 |     a::io_context::work work(io_service);
      |                    ^~~~
```

fix: remove `boost::asio::io_service::work`

```
In file included from /home/user/src/libtorrent/libtorrent-issue7926-2/kademlia/test/unit_tests/test_store_value_task.cpp:27:
/home/user/src/libtorrent/libtorrent-issue7926-2/kademlia/test/unit_tests/tracker_mock.hpp: In member function 'void kademlia::test::tracker_mock::send_request(const RequestType&, const EndpointType&, const TimeoutType&, const OnMessageReceiveCallback&, const OnErrorCallback&)':
/home/user/src/libtorrent/libtorrent-issue7926-2/kademlia/test/unit_tests/tracker_mock.hpp:127:26: error: 'post' is not a member of 'boost::asio'
  127 |             boost::asio::post( io_service_, [ on_error ]( void )
      |                          ^~~~
```

```diff
+#include <boost/asio/post.hpp>
```

### test

```
$ ctest
Test project /home/user/src/libtorrent/libtorrent-issue7926-2/kademlia/build
      Start  1: unit_tests_helpers
 1/26 Test  #1: unit_tests_helpers ...............***Failed    0.08 sec
      Start  2: test_id
 2/26 Test  #2: test_id ..........................   Passed    0.08 sec
      Start  3: test_endpoint
 3/26 Test  #3: test_endpoint ....................   Passed    0.05 sec
      Start  4: test_boost_to_std_error
 4/26 Test  #4: test_boost_to_std_error ..........   Passed    0.02 sec
      Start  5: test_message
 5/26 Test  #5: test_message .....................   Passed    0.06 sec
      Start  6: test_message_serializer
 6/26 Test  #6: test_message_serializer ..........   Passed    0.06 sec
      Start  7: test_lookup_task
 7/26 Test  #7: test_lookup_task .................   Passed    0.01 sec
      Start  8: test_store_value_task
 8/26 Test  #8: test_store_value_task ............   Passed    0.01 sec
      Start  9: test_find_value_task
 9/26 Test  #9: test_find_value_task .............   Passed    0.02 sec
      Start 10: test_ip_endpoint
10/26 Test #10: test_ip_endpoint .................   Passed    0.01 sec
      Start 11: test_peer
11/26 Test #11: test_peer ........................   Passed    0.01 sec
      Start 12: test_error
12/26 Test #12: test_error .......................   Passed    0.01 sec
      Start 13: test_discover_neighbors_task
13/26 Test #13: test_discover_neighbors_task .....   Passed    0.01 sec
      Start 14: test_notify_peer_task
14/26 Test #14: test_notify_peer_task ............   Passed    0.01 sec
      Start 15: test_response_router
15/26 Test #15: test_response_router .............   Passed    0.01 sec
      Start 16: test_response_callbacks
16/26 Test #16: test_response_callbacks ..........   Passed    0.01 sec
      Start 17: test_timer
17/26 Test #17: test_timer .......................***Failed    0.01 sec
      Start 18: test_network
18/26 Test #18: test_network .....................   Passed    0.01 sec
      Start 19: test_message_socket
19/26 Test #19: test_message_socket ..............   Passed    5.08 sec
      Start 20: test_log
20/26 Test #20: test_log .........................   Passed    0.01 sec
      Start 21: test_r
21/26 Test #21: test_r ...........................   Passed    0.01 sec
      Start 22: test_routing_table
22/26 Test #22: test_routing_table ...............   Passed    0.01 sec
      Start 23: test_session
23/26 Test #23: test_session .....................   Passed    0.22 sec
      Start 24: test_first_session
24/26 Test #24: test_first_session ...............   Passed    0.02 sec
      Start 25: test_concurrent_guard
25/26 Test #25: test_concurrent_guard ............   Passed    0.01 sec
      Start 26: test_engine
```

### fixme

fixme: `test_engine` hangs with 100% cpu load

```
$ ./test/unit_tests/test_engine
Running 3 test cases...
```

### CODE REVIEW

**Comment by milahu** [comment]
> Without this commit: [7cdf78b](https://github.com/DavidKeller/kademlia/commit/7cdf78bda780b044e6f23542b7aba72a7a1a97c1), all tests are fine.

sure you are using boost 1.87?

when i revert 7cdf78bda780b044e6f23542b7aba72a7a1a97c1 then the build fails with

```
kademlia/test/unit_tests/test_fake_socket.cpp: In member function ‘void {anonymous}::fake_socket::test_construction::can_send_and_receive_messages::test_method()’:
kademlia/test/unit_tests/test_fake_socket.cpp:104:20: error: ‘work’ is not a member of ‘boost::asio::io_context’
  104 |     a::io_context::work work(io_service);
      |                    ^~~~
kademlia/test/unit_tests/test_fake_socket.cpp: In member function ‘void {anonymous}::fake_socket::test_construction::can_detect_closed_socket::test_method()’:
kademlia/test/unit_tests/test_fake_socket.cpp:189:20: error: ‘work’ is not a member of ‘boost::asio::io_context’
  189 |     a::io_context::work work(io_service);
      |                    ^~~~
kademlia/test/unit_tests/test_fake_socket.cpp: In member function ‘void {anonymous}::fake_socket::test_construction::can_send_and_receive_messages_to_self::test_method()’:
kademlia/test/unit_tests/test_fake_socket.cpp:236:20: error: ‘work’ is not a member of ‘boost::asio::io_context’
  236 |     a::io_context::work work(io_service);
      |                    ^~~~
```

so maybe this needs a version switch for backward compatibility?

my test build is

```sh
git clone --depth 1 --recurse-submodules https://github.com/milahu/libtorrent-issue7926-2
cd libtorrent-issue7926-2
nix-shell
mkdir build
cd build
cmake ..
make
```

**Comment by DavidKeller** [comment]
LGTM :-)

Please note that I'm working on another version of this library, using modern C++20, CMake and vcpkg.

There are some pending issues with this version of the library I won't fix given I don't find the spare time to maintain it while creating the new version. I'll point to the new version once there is feature parity.

**Comment by DavidKeller** [comment]
Hi @milahu, I've updated the project to use CMake 3 and more importantly use Gitlab actions and VCPKG.

Please rebase on `master` and update the [VCPKG baseline](https://github.com/DavidKeller/kademlia/blob/21b086131f212bb42f01118164b180fe0b501f9a/vcpkg.json#L3)  to `365f6444ab40ee87c73c947b475b3a267b3cb77c` in order to use latest boost.

**Comment by milahu** [comment]
done, but now `cmake` cannot find `openssl`

```
$ rm -rf build/; mkdir build; cd build; cmake ..
-- The CXX compiler identification is GNU 14.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /nix/store/pbqah1qk4b5y14fqinr1h8zvhqy71v81-gcc-wrapper-14.3.0/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
CMake Error at cmake/dependencies.cmake:19 (find_package):
  Could not find a package configuration file provided by "OpenSSL" with any
  of the following names:

    OpenSSLConfig.cmake
    openssl-config.cmake

  Add the installation prefix of "OpenSSL" to CMAKE_PREFIX_PATH or set
  "OpenSSL_DIR" to a directory containing one of the above files.  If
  "OpenSSL" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:8 (include)
```

but `openssl` is installed in my build env

```
$ echo $CMAKE_INCLUDE_PATH | tr : $'\n' | grep -i openssl
/nix/store/k0699a27nkj4c2xn67bjcpfa08nqn9l4-openssl-3.4.1-dev/include

$ echo $CMAKE_LIBRARY_PATH | tr : $'\n' | grep -i openssl
/nix/store/byx7ahs386pskh8d5sdkrkpscfz9yyjp-openssl-3.4.1/lib
```

on nixos linux, the `openssl` package has no `OpenSSLConfig.cmake`

```
$ nix-locate --top-level OpenSSLConfig.cmake
quictls.dev                                       5,615 r /nix/store/79l9mmdsrn1x6p70n8hj612kkzjl7bf8-quictls-3.3.0-quic1-dev/lib/cmake/OpenSSL/OpenSSLConfig.cmake

$ nix-locate --top-level openssl-config.cmake

$ nix-locate --top-level FindOpenSSL.cmake
cmake.out                                        28,529 r /nix/store/ad4c8nx2lkjs4zq0sj9jdpn7w45v9ccs-cmake-3.31.6/share/cmake-3.31/Modules/FindOpenSSL.cmake
```


fix: remove `CONFIG` in `cmake/dependencies.cmake`

```diff
-find_package(OpenSSL CONFIG REQUIRED)
+find_package(OpenSSL REQUIRED)
```

at least this fixes the build
i have still not tested this on runtime
